### ISSUE TITLE
Deleted question shows up in search suggestion

### ISSUE THREAD

**Issue by gaurav517** [drodil/backstage-plugin-qeta#107]
Deleted question shows up in search suggestion. In example below, `Test Question` has been deleted but it still shows up when trying to search for that.

![image](https://github.com/drodil/backstage-plugin-qeta/assets/15346341/78ad3dfd-76c1-4e27-9e37-91f02952d94c)

**Comment by drodil** [comment]
It will take some time for the collator to run again and remove the question from search index. Same thing for other backstage collators like for the catalog; if you remove something from catalog it might still be in the search index and show up as result.

**Comment by gaurav517** [comment]
okay.. how long if know? I still see it 2 days after deletion.

**Comment by drodil** [comment]
Depends how you have configured the collator (https://github.com/drodil/backstage-plugin-qeta/blob/main/plugins/qeta-backend/src/search/collators/QetaCollatorFactory.ts). It doesn't have scheduling as it's own. What search backend do you use? Do you have some cleaning for that?
