### ISSUE TITLE
Qeta backend failing with 500 for search requests with special characters included

### ISSUE THREAD

**Issue by TheAlmightyMight** [drodil/backstage-plugin-qeta#110]
Hello, dear friends. Here's the gist of it: some of the characters that could trigger such behavior  are : /  \  and sometimes it fails when combined with other ASCII and cyrillic characters. So special characters are the culprit I guess. 

Consider this url https://backstage.pyn.ru/api/qeta/questions?limit=10&includeEntities=true&order=desc&orderBy=created&noAnswers=false&noCorrectAnswer=false&noVotes=false&searchQuery=Cannot+read+config+file%3A.

An example response for that would be: 

`
{
"error": {
"name": "error",
"message": "select \"questions\".*, (select sum(\"score\") from \"question_votes\" where \"question_votes\".\"questionId\" = \"questions\".\"id\") as \"score\", (select count(*) from \"question_views\" where \"question_views\".\"questionId\" = \"questions\".\"id\") as \"views\", (select count(*) from \"answers\" where \"answers\".\"questionId\" = \"questions\".\"id\") as \"answersCount\", (select count(*) from \"answers\" where \"answers\".\"questionId\" = \"questions\".\"id\" and \"answers\".\"correct\" = $1) as \"correctAnswers\", (select count(*) from \"user_favorite\" where \"user_favorite\".\"user\" = $2 and \"user_favorite\".\"questionId\" = \"questions\".\"id\") as \"favorite\" from \"questions\" left join \"question_votes\" on \"questions\".\"id\" = \"question_votes\".\"questionId\" left join \"question_views\" on \"questions\".\"id\" = \"question_views\".\"questionId\" left join \"answers\" on \"questions\".\"id\" = \"answers\".\"questionId\" left join \"user_favorite\" on \"questions\".\"id\" = \"user_favorite\".\"questionId\" where (to_tsvector('english', questions.title || ' ' || questions.content) @@ websearch_to_tsquery('english', $3)\n          or to_tsvector('english', questions.title || ' ' || questions.content) @@ to_tsquery('english',$4)) group by \"questions\".\"id\" order by \"created\" desc limit $5 - syntax error in tsquery: \"Cannot+read+config+file::*\"",
"length": 257,
"severity": "ERROR",
"code": "42601",
"where": "unnamed portal with parameters: $1 = 'true', $2 = 'user:default/guest', $3 = 'Cannot read config file:', $4 = 'Cannot+read+config+file::*', $5 = '10'",
"file": "tsquery.c",
"line": "723",
"routine": "makepol"
},
"request": {
"method": "GET",
"url": "[/questions?limit=10&includeEntities=true&order=desc&orderBy=created&noAnswers=false&noCorrectAnswer=false&noVotes=false&searchQuery=Cannot+read+config+file%3A](https://backstage.pyn.ru/questions?limit=10&includeEntities=true&order=desc&orderBy=created&noAnswers=false&noCorrectAnswer=false&noVotes=false&searchQuery=Cannot+read+config+file%3A)"
},
"response": {
"statusCode": 500
}
}
`

Is this expected behavior?

**Comment by drodil** [comment]
Some pointers:
- https://github.com/drodil/backstage-plugin-qeta/blob/main/plugins/qeta-backend/src/database/DatabaseQetaStore.ts#L122
- https://dba.stackexchange.com/questions/135030/filtering-special-characters-in-to-tsquery

Should implement a fix and add test for that, might take a look at some point I have time. Feel free to contribute if someone comes up with a fix!
