### ISSUE TITLE
feat: searching resets the page

### ISSUE THREAD

**Issue by rcelebrone** [drodil/backstage-plugin-qeta#112]
When we search for a term, it should reset page to page 1:

```
const onSearchQueryChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setPage(1);
    setSearchQuery(event.target.value);
};
```

https://github.com/drodil/backstage-plugin-qeta/blob/748d9981c554850e5f0d2533bbce709a7b05cb2b/plugins/qeta/src/components/QuestionsContainer/QuestionsContainer.tsx#L77

**Comment by rcelebrone** [comment]
@drodil what do you think?

**Comment by drodil** [comment]
Makes sense. Also for other filters
