### ISSUE TITLE
bug: text does not wrap line when using code block

### ISSUE THREAD

**Issue by caioq** [drodil/backstage-plugin-qeta#118]
The text in question and answer does not wrap line when using code block markdown \``` .

Example:
![image](https://github.com/drodil/backstage-plugin-qeta/assets/19962665/dbab51d1-d48e-4c6e-8b8c-eacedcc70c8c)

**Comment by drodil** [comment]
The plugin uses `MarkdownContent` from backstage core-components to render the question and answer content. I am not sure if it can be fixed in the plugin side but let's see. If someone has time to take a look, feel free to do so!

**Comment by drodil** [comment]
What does github do by the way:

```js
animals.push('chickens', 'cats', 'dogs', 'pigs', 'goats', 'sheep', 'cows', 'lions', 'giraffes', 'penguins', 'mice');
```

**Comment by caioq** [comment]
I'm closing this issue because this behavior is not happening anymore after the latest release.
