### ISSUE TITLE
Upvote/downvote count not updating automatically

### ISSUE THREAD

**Issue by gabriel-dantas98** [drodil/backstage-plugin-qeta#124]
Despite clicking on the buttons and the call to the backend working normally, the values are not updating :/
![2024-02-27 08 24 55](https://github.com/drodil/backstage-plugin-qeta/assets/20074620/400e4339-2a4b-4bee-a395-4465fe927ddb)

**Comment by drodil** [comment]
Thanks for this. Missed it when integrated signals to the plugin. Fix coming up!
