### ISSUE TITLE
Possibility of changing the color of the home page header.  

### ISSUE THREAD

**Issue by gabriel-dantas98** [drodil/backstage-plugin-qeta#129]
Internally, we've given the q&a plugin a different name, and we'd like to change the color of the header.  But from what I've investigated, we'd have to make it a component prop.

https://github.com/drodil/backstage-plugin-qeta/blob/40560c1dbbf3258cc867bd67b07cb1daf0a0a7ab/plugins/qeta/src/components/HomePage/HomePage.tsx#L176-L177

**Comment by drodil** [comment]
Good idea, will add this to the next release soonish
