### ISSUE TITLE
With list of allowedTags and allowCreation false configuration tags are not getting attached to question

### ISSUE THREAD

**Issue by kedaroh-bh** [drodil/backstage-plugin-qeta#139]
- [X] I tried to find this or similar issue but didn't found.

**Description:**
I have a requirement that we don't want end user to create new tag and they can choose only from predefined tags, so I have configured _allowedTags_ to few pre-defined tags and set the _allowCreation_ to false. However when I attach/select a tag on Ask Question form and post the question the tag is not showing on question.

**Steps to reproduce:**
1. Configure _allowedTags_ to list of tags and _allowCreation_ set to false, in app-config.yaml
2. Click "Ask question" button
3. Fill the form and select tag from the list.
4. Post the question
5. In question tile from question list tag is not displayed.

Attached screenshot question "test5"

However if I set allowCreation to true and add few tags in tags table manually and then post a question with tag then it working fine, screenshot question "test4"

**Findings:**
in plugins\qeta-backend\src\service\routes\questions.ts getTags method below line is filtering out the selected tag when allowCreation is false.

![image](https://github.com/drodil/backstage-plugin-qeta/assets/138849700/66f6dab2-3da1-4183-9e55-0d24376d1562)

![image](https://github.com/drodil/backstage-plugin-qeta/assets/138849700/ca96159a-16e4-48ca-9500-08ba97ac55d0)

**Comment by drodil** [comment]
Hi, good find! I think the filter is wrong and the allowedTags.includes should not be negated like it is now. Do you have possibility to try it out with that change and perhaps submit a PR? I can take a look once I am back from easter vacation next week some time.

**Comment by kedaroh-bh** [comment]
Hi @drodil, I saw your reply today and looks like you fixed it already, thank you.
