### ISSUE TITLE
SignIn Error

### ISSUE THREAD

**Issue by reddkas-bh** [drodil/backstage-plugin-qeta#149]
After click on Enter button on Sign In home page, getting error as TypeError. 
![Q A_SignIn](https://github.com/drodil/backstage-plugin-qeta/assets/150109548/f1573cf3-2d32-4b63-b8db-d6a5207aefff)
![Q A_Error_after_SignIn](https://github.com/drodil/backstage-plugin-qeta/assets/150109548/d9a2c7e6-055e-488f-be25-5ee5b2828b1f)

**Comment by drodil** [comment]
Where is this happening? On your instance?

**Comment by reddkas-bh** [comment]
Issue got fixed. There was an issue in my local pgsql db connection.
