### ISSUE TITLE
Question: Can we use this plugin with old backend system of backstage ?

### ISSUE THREAD

**Issue by kedaroh-bh** [drodil/backstage-plugin-qeta#156]
We have not migrated our Backstage instance to new Backend system and we need a fix for issue #154 
1. Is it fine to use latest frontend plugin with old backend plugin version ?
2. Can we use this plugin with old backend system ?

**Comment by drodil** [comment]
1. It should be fine, I don't think there's major api changes lately
2. I've removed support for the old backend system on purpose to make people migrate to the new. This is also what's happening in the backstage repo all the time. So, I would suggest you to also do the migration asap

**Comment by kedaroh-bh** [comment]
Thank you for quick response, we will start migration to new backend system.
