### ISSUE TITLE
bug: upload attachment with database storage saving attachments to database as well as file system

### ISSUE THREAD

**Issue by kedaroh-bh** [drodil/backstage-plugin-qeta#163]
There should if-else ladder, in case of 'database' storage it is going in 'database' and default condition

https://github.com/drodil/backstage-plugin-qeta/blob/main/plugins/qeta-backend/src/service/routes/attachments.ts#L85

As it is returning response twice, hence receiving unhandled error "Unhandled rejection Cannot set headers after they are sent to the client"

**Comment by drodil** [comment]
Good catch, I will make a fix!
