### ISSUE TITLE
Migrate to new backstage auth services

### ISSUE THREAD

**Issue by christianherweg0807** [drodil/backstage-plugin-qeta#167]
Since we updated all of our backstage plugins to the new backend & auth Services. We got an error message from the search-backend-module-qeta:

Someting like:
`Collating documents for qeta failed: Error: Unable to generate legacy token, no legacy keys are configured in 'backend.auth.keys' or 'backend.auth.externalAccess'`

I think this is because you are using still the coreServices.tokenManager instead of coreServices.httpAuth.

https://github.com/drodil/backstage-plugin-qeta/blob/50b6af61d27aba6eaf5148b0f9fbeb6cfb252360/plugins/search-backend-module-qeta/src/module.ts#L18-L38

There is a good migration guide:
https://backstage.io/docs/tutorials/auth-service-migration/

Would be wonderful, if we could through away the old auth service & config.

regards
Christian

**Comment by drodil** [comment]
Ah, true, good catch. Other plugins were already migrated to the new backend system. I will make a fix for this, thanks for reporting!

**Comment by christianherweg0807** [comment]
Should be just a small change...

**Comment by drodil** [comment]
Already released in v2.4.1, please try it out 👍

**Comment by christianherweg0807** [comment]
LGTM.  👍

Thank you for this blazing fast release.
