### ISSUE TITLE
feat: allow service-to-service requests for marking answers correct

### ISSUE THREAD

**Issue by raphtalia** [drodil/backstage-plugin-qeta#172]
I'm currently importing questions from Stackoverflow to Qeta but my script is unable to mark answers correct unless I supply a user token.

**Comment by drodil** [comment]
I am making a fix for this so that service tokens can be used to mark correct answers. Also, it's possible to add votes with a service token and use the query parameter `?score=10` with the `/questions/:id/answers/:answerId/upvote` path.
