### ISSUE TITLE
Users should be warned if they try to navigate away from before saving their entry

### ISSUE THREAD

**Issue by RomanSaveljev** [drodil/backstage-plugin-qeta#175]
I think nowadays many websites adopted a practice of notifying a user about data loss, if they try to navigate away before saving/submitting their form. I could accidentally hit "go back" shortcut or reload the page and lose my entry.

Q&A does not implement this and it could leave some people unsatisfied with the UX (because they got used to this feature). Please consider if it should be added to the Q&A plugin.

FYI @drodil

**Comment by Teemukoivumaa** [comment]
Working on implementing this now
