### ISSUE TITLE
Entity Owner Permissions

### ISSUE THREAD

**Issue by marct83** [drodil/backstage-plugin-qeta#184]
Is there a way to create a permissions policy to only allow permissions on questions that are tied to entities you own?

**Comment by drodil** [comment]
Hi, 

Yes it's actually possible with the latest release. See an example here: https://github.com/drodil/backstage-plugin-qeta/blob/main/plugins%2Fqeta-backend%2Fdev%2FPermissionPolicy.ts#L73 and docs for more information how to enable the permissions: https://github.com/drodil/backstage-plugin-qeta/blob/main/docs%2Fpermissions.md

If you run in to any issues or have ideas how to improve this, please let me know or open a PR directly!

Thanks!

**Comment by marct83** [comment]
Thanks for the reply. In the example it's a list of hardcoded entities. Is it possible to just use the entities that are added to the question and verify the user owns those entities?

**Comment by drodil** [comment]
Hmm. Actually you have to use catalog api to fetch the owned entities. The q&a plugin knows only the entity reference attached to a question, not the entity owner. If you manage to set this up, could you provide an example as a PR? I might have to look at this myself at some point as well.
