### ISSUE TITLE
Sign-In Button Lacks Border

### ISSUE THREAD

**Issue by anushkabhansalii** [drodil/backstage-plugin-qeta#185]
**Description:**
The sign-in button currently lacks a border, which makes it visually inconsistent compared to the sign-up button. This inconsistency can create confusion for users and impact the overall aesthetic of the interface.

**Steps to Reproduce:**
1. Navigate to the login or sign-up page.
2. Observe the appearance of the sign-in button and compare it with the sign-up button.
3. Note that the sign-in button does not have a border, while the sign-up button does.
![Screenshot from 2024-10-16 11-31-06](https://github.com/user-attachments/assets/8e5d5fc1-b81f-4957-ab92-18afa2c4cc15)

**Comment by drodil** [comment]
@anushkabhansalii sorry, but where is this button located? I think you have wrong repository..
