### ISSUE TITLE
Refactor frontend plugin 

### ISSUE THREAD

**Issue by drodil** [drodil/backstage-plugin-qeta#197]
Refactor the frontend plugin so that  most of the components live in the react package instead.

Also move the API and Client to common package so that it can be used also from the search collator and other backend plugins.

**Comment by muralimeka** [comment]
Hello @drodil not sure if this was done on purpose but plugins/qeta-react/src/components/QuestionsContainer/QuestionsContainer.tsx files are missing but catalog integration(https://github.com/drodil/backstage-plugin-qeta/blob/main/docs/catalog.md) still refers to that component which is missing in 3.3.0. This is causing issues in EntityPage.tsx as it complains about missing packages AskForm and
  QuestionsContainer cmponents. 

Please let me know if I'm missing something as I didn't see any comments on release notes regarding replacement of the files.

**Comment by drodil** [comment]
Hey. The name of this component changed to PostsContainer and it was moved to qeta-react package so that it can be used also from other frontend plugins. Sorry but I didn't pay too much attention to the migration steps though updated the docs.

**Comment by drodil** [comment]
Updated the docs now, might write an migration guide next week!

**Comment by muralimeka** [comment]
Hello @drodil , thanks for quick updates. I tried using PostsContainer even before you mentioned it but wasn't sure if Questions and Posts were the same thing. Checked out the migration guide and thanks for adding that, it will be helpful for others.

Also eslint was complaining about showTitle and showAskButton with **Value must be omitted for boolean attribute `showTitle`eslint[react/jsx-boolean-value](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-boolean-value.md)**. The recommendation from vscode was to remove the boolean value that we were setting to true.

**Comment by drodil** [comment]
Questions and posts are the same thing now, just that the posts are now typed to be either articles or questions. You can pass the type to PostsContainer if you want to show only questions.

We are also using the showAskButton so I wonder why it's complaining 🤔

**Comment by drodil** [comment]
See also short migration guide at https://github.com/drodil/backstage-plugin-qeta/blob/main/docs%2Findex.md

**Comment by drodil** [comment]
Here's also one example: https://github.com/drodil/backstage-plugin-qeta/blob/main/plugins%2Fqeta%2Fdev%2FComponentPage.tsx

**Comment by muralimeka** [comment]
Right, the above declaration works where we don't set those to true but the documentation suggested we set the below
 showTitle={true}
 showAskButton={true}.

Probably needs another update to documentation.

**Comment by drodil** [comment]
Oh yes, I will update that, thanks for pointing out!
