### ISSUE TITLE
AI Integration

### ISSUE THREAD

**Issue by drodil** [drodil/backstage-plugin-qeta#220]
Create an extension point to the Q&A backend that can be utilized to get AI answers for questions. The extension point should provide a method where the question title and content are passed and it should return an AI response to the question from custom functionality. This allows the plugin users to utilize their own AI functionalities with the plugin without the need to integrate some specific one into the plugin itself.

**Comment by gabriel-dantas98** [comment]
That would be a very cool thing to do, and we're exploring the possibility here in the team.

Some use cases we've thought of to help with ideas:

- Suggested answers before a question is opened
- Automated related answers in the same style as the AWS documentation
![image](https://github.com/user-attachments/assets/5d8f2874-f359-4492-8620-47c21ac63562)

**Comment by drodil** [comment]
Yeah, we are also evaluating this as we have custom AI support already in our Backstage instance, and with an extension point, it would be possible to attach the custom functionality to this plugin. Of course, it would be possible to provide a backend module for example for ChatGPT that could be used if wanted.

**Comment by drodil** [comment]
The first version is done, it will show the AI answer on the question page (after it has been posted though), but more features are now implementable!

**Comment by drodil** [comment]
Added also AI integration to the ask page so it will propose an answer before posting the question:
![image](https://github.com/user-attachments/assets/f10f5263-1822-42d6-b609-c4420e41a1e4)

The content must be longer than 20 characters not to call the AI unnecessarily and there's also 3 second debounce before fetching new answer. @gabriel-dantas98 what do you think?

**Comment by drodil** [comment]
Now there's ready-made module to integrate with OpenAI, docs here: https://github.com/drodil/backstage-plugin-qeta/blob/main/docs/ai.md
