### ISSUE TITLE
feat: add props title and subtitle for QuetaPage header

### ISSUE THREAD

**Issue by accezar** [drodil/backstage-plugin-qeta#23]
Add props for `<QetaPage />` component allowing the developer to set a `string` for page title and subtitle.

**Comment by drodil** [comment]
Good idea and not a big change!

**Comment by drodil** [comment]
Just released this in v1.1.0. Feel free to test it out :)

**Comment by accezar** [comment]
Super duper fast!! this is awesome! @drodil
