### ISSUE TITLE
QetaContent: Error: No path for routeRef{type=sub,id=qeta.ask}

### ISSUE THREAD

**Issue by FilipSwiatczak** [drodil/backstage-plugin-qeta#234]
hey @drodil , 

Thanks for making the plugin, it's great! 

With recent leap upgrade from "@drodil/backstage-plugin-qeta": "**2.2.1**" to 
"@drodil/backstage-plugin-qeta": "**3.5.1**",
    "@drodil/backstage-plugin-qeta-react": "^**3.7.1**",
    
 the Q&A tab on all entities started throwing the error:
 `Error: No path for routeRef{type=sub,id=qeta.ask}`
 
 This is my QetaContent component and I have followed the migration guide (https://github.com/drodil/backstage-plugin-qeta/blob/main/docs/migration.md) :
 
 ``` import { Container } from '@material-ui/core';
import React from 'react';
import { PostsContainer } from '@drodil/backstage-plugin-qeta-react';

export const QetaContent = () => {
  return (
    <Container>
      <PostsContainer
        showTitle
        showAskButton
        type="question" // Can be 'question' or 'article' or none
      />
    </Container>
  );
};
```

Backstage"version": "1.32.3"
Node: node:20-bookworm-slim

Does it need additional Route registration in the app/src/App.tsx? Besides the base:
`<Route path="/qeta" element={<QetaPage title="Questions" />} />`
Thanks!

**Comment by drodil** [comment]
Hi, it should not need an additional route to App.tsx, at least not in our setup nor in the local dev app in this repo. The askRoute is sub route for the root: https://github.com/drodil/backstage-plugin-qeta/blob/main/plugins/qeta-react/src/routes.ts#L7

I recommend using the same versions for all q&a packages just to be sure they are compatible!

**Comment by drodil** [comment]
Do you have the `qeta` plugin installed in `app` and main menu item using `QetaPage` or route binding in `App.tsx`?

**Comment by FilipSwiatczak** [comment]
thanks @drodil!
I've upgraded `backend`, `qeta` and `qeta-react` to the same version **3.9.2** and it solved it. 

Hopefully useful error reference for anyone running into this. My Yarn 1 to 4 upgrade may have had something to do with the latest version of the package not being suggested earlier. 
Thanks, closing!
