### ISSUE TITLE
🐛  Tags selector is not visible on the UI

### ISSUE THREAD

**Issue by leonarhv** [drodil/backstage-plugin-qeta#235]
# What

The Tags selector is not visible and does not allow users to select tag while creating questions

# Version

"@drodil/backstage-plugin-qeta": "^3.9.2",

# Prints

![Captura de Tela 2024-11-04 às 16 39 10](https://github.com/user-attachments/assets/cd275a33-4b08-4701-807e-ed581301c3a2)

Is this expected? Are there any new configurations for this?

**Comment by drodil** [comment]
Thanks for finding this, it was a bug that it didn't show it if there were no existing tags. Fixed now, will push a patch release soon!
