### ISSUE TITLE
Wrong questions without correct answers

### ISSUE THREAD

**Issue by Vsevolod123** [drodil/backstage-plugin-qeta#26]
Hi!

It looks like a bug
https://github.com/drodil/backstage-plugin-qeta/blob/4ab4ddd4f3f70a3a1fcb09d3ca29afcb3e06d497/plugins/qeta-backend/src/database/DatabaseQetaStore.ts#L297

This query checks that question has no answers or has incorrect answers, but I think it should check that question hasn't correct answer.

Thank you!

**Comment by drodil** [comment]
Hi,
But it's the same thing. One question can only have one correct answer.

**Comment by Vsevolod123** [comment]
Yes, question can have many incorrect answers

**Comment by drodil** [comment]
Oh true, it seems like a bug. Any ideas what would be the correct SQL?

**Comment by Vsevolod123** [comment]
add some `LEFT JOIN answers correct_answer ON correct_answer.question_id = questions.id AND correct_answer.correct = TRUE` and add to where section condition `correct_answer.id IS NULL` if type = 'incorrect'

**Comment by drodil** [comment]
Nice, I will try that! Thanks.

**Comment by drodil** [comment]
No problem, thanks for reporting!
