### ISSUE TITLE
Tags page is empty

### ISSUE THREAD

**Issue by Vsevolod123** [drodil/backstage-plugin-qeta#27]
Page /qeta/tags/:tag is empty

**Comment by drodil** [comment]
What tag did you use? The :tag should be replaced with some tag used in any question.

**Comment by Vsevolod123** [comment]
just blank page

![image](https://user-images.githubusercontent.com/10753618/212251989-21bdd32d-4b1f-4185-8de2-4d97bf856a2f.png)

**Comment by drodil** [comment]
![image](https://user-images.githubusercontent.com/1178319/212252096-e226091c-c707-45d1-9028-0bb91d2e4ac7.png)

I think you are missing the path parameter. See the image above. It might be that I have to add a page to tell there are no questions if the tag doesn't exist. What version are you using?

**Comment by Vsevolod123** [comment]
version of plugin is 1.1.0

i have tag "test", and some tagged question but /qeta/tags/test is blank, and /qeta/tags is blank too

**Comment by drodil** [comment]
Hm, that's weird. I haven't been able to reproduce it in my backstage instance nor in the plugin environment. Do questions and author pages work for you ( /qeta/questions/:id and /qeta/user/:user_id )?

**Comment by Vsevolod123** [comment]
I'll try to investigate cause of this problem and will leave feedback if find

**Comment by Vsevolod123** [comment]
and yes, everything works but tags

**Comment by drodil** [comment]
The only difference I find is the use of optional :tag in the route:
```
<Route path="/tags/:tag?" element={<TagPage />} />
```
Could that explain it?

**Comment by drodil** [comment]
If I change it like this, both still work fine:
```
      <Route path="/tags" element={<TagPage />} />
      <Route path="/tags/:tag" element={<TagPage />} />
```
Do you think this would fix the problem at your end?

**Comment by drodil** [comment]
I will give it a go and release a patch version with this fix. It might be better anyways for backwards compatibility.

**Comment by drodil** [comment]
It will be bumped to 1.2.0 since there is also one new feature. But try that out, it should be available in couple of minutes.

**Comment by drodil** [comment]
Sorry, it is 1.1.1, just released.

**Comment by Vsevolod123** [comment]
It works! Thank you!

**Comment by drodil** [comment]
No problem, thanks for reporting!
