### ISSUE TITLE
Can't vote multiple answers in one question

### ISSUE THREAD

**Issue by Vsevolod123** [drodil/backstage-plugin-qeta#28]
Hi!

https://github.com/drodil/backstage-plugin-qeta/blob/4d5fa57a0111d33cddab595a48b9e64c33c07651/plugins/qeta-backend/src/database/DatabaseQetaStore.ts#L630

Is it right logic that I can vote for only one answer in one question?

**Comment by drodil** [comment]
No, it should actually also check the question id. I will check and fix that, thanks for reporting!

**Comment by drodil** [comment]
Should be fixed in 1.1.2, thanks again for reporting!

**Comment by Vsevolod123** [comment]
Yes, it works correct! Thank you again!
