### ISSUE TITLE
Search result opens in a new tab

### ISSUE THREAD

**Issue by gaurav517** [drodil/backstage-plugin-qeta#29]
Clicking on search result for Q&A opens in new tab. Its not same for other results.

In the screenshot below, if I click on `Test Question`, Question page opens in a new tab.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/15346341/213158205-46b69bff-2274-437b-9e34-c018916e77b1.png">

**Comment by drodil** [comment]
Thanks for the report. It might be that the Backstage search treats all locations that have protocol defined as external links that are opened in a new window. Basically removing the baseUrl from https://github.com/drodil/backstage-plugin-qeta/blob/main/plugins/qeta-backend/src/search/collators/QetaCollatorFactory.ts#L65 could help though it should be tested as I am not sure if my assumption is correct. Apparently default result list item is used: https://github.com/backstage/backstage/blob/master/plugins/search-react/src/components/DefaultResultListItem/DefaultResultListItem.tsx#L76

From usability point of view I don't mind opening search results in new window as you may want to get back to the list of results which does not work with back button.

**Comment by gaurav517** [comment]
`I don't mind opening search results in new window`: User can always right click and open in new tab if they want to. Problem here is the inconsistency with other search results.. which is a bad user experience.

**Comment by drodil** [comment]
True, I will check if changing the path to relative fixes this issue

**Comment by drodil** [comment]
New release 1.2.1 is being released soon, could you try with that? Thanks!

**Comment by drodil** [comment]
@gaurav517 did the new version solve this for you?

**Comment by gaurav517** [comment]
No.. its same with new version.. I think its opening in new tab because of `target="_blank"`. A comparison of two results in html:
![image](https://user-images.githubusercontent.com/15346341/213827728-1055e831-8313-4586-b708-0eed2415253c.png)

**Comment by drodil** [comment]
Hm. But it's not the plugin that renders the links.. It only provides the location to Backstage. No idea how to fix this at the moment.

**Comment by drodil** [comment]
You can see the collator functionality here: https://github.com/drodil/backstage-plugin-qeta/blob/main/plugins/qeta-backend/src/search/collators/QetaCollatorFactory.ts#L63
