### ISSUE TITLE
feat: track user discussions

### ISSUE THREAD

**Issue by leonarhv** [drodil/backstage-plugin-qeta#32]
# What
It would be nice if the plugin had easy access to questions created by you.

The current navigation doesn't offer a friendly interface to manage your entries, especially if the organization has many questions
![Captura de Tela 2023-01-31 às 23 01 26](https://user-images.githubusercontent.com/53581258/215927099-1a3f315a-55f6-4e47-97fb-eac324ceda3c.png)

# Possible implementation

There is already a great path built to check the questions of a specific user. A button on the main page redirecting to your user questions would be a great addition.

![Captura de Tela 2023-01-31 às 23 01 39](https://user-images.githubusercontent.com/53581258/215927449-86b4ad04-bd75-462c-a8e7-2d8e83418c2e.png)

**Comment by drodil** [comment]
Good idea. Maybe it could be added next to the `Tags` button. Or maybe it could be a dropdown for both `Tags` and `My questions` just in case there is more navigation to come.

**Comment by drodil** [comment]
Released in 1.3.0, please try it out!
