### ISSUE TITLE
ux: Light Theme Accessibility

### ISSUE THREAD

**Issue by alecjacobs5401** [drodil/backstage-plugin-qeta#37]
### Description

Backstage instances that use a [Custom Theme](https://backstage.io/docs/getting-started/app-custom-theme#__docusaurus) (or the builtin Light Theme) have a few accessibility issues when it comes to some of the component variant usage/colors.

Primarily, the Buttons to Create new Questions blend in with the background and look like they are `disabled` and not actionable at  an immediate glance

#### Landing Page with no Questions Asked
![image](https://user-images.githubusercontent.com/12898497/217041666-7787c3e1-eff1-4600-80fa-66cb5c7b1b04.png)

* The `Go Ahead and Ask One!` button looks like just plain text
* The `Ask Question` in the top right doesn't look actionable and is hard to see immediately

#### Asking a Question
![image](https://user-images.githubusercontent.com/12898497/217041941-7ed0e787-0ed5-4dca-aadf-59ad9b2f608b.png)

* The `POST` button in the bottom left to submit the Form looks like it is `disabled` and not actionable when the question is properly filled out

#### Answering a Question
![image](https://user-images.githubusercontent.com/12898497/217042194-307e7615-fdf3-4ef6-a244-ec04ad0961e4.png)

Similar issues, most buttons blend into background or look `disabled`

### Expected Behavior
These buttons should respect the configured `primary` theme colors defined in a Backstage instance

For example, our theme uses a Lighter Green for Primary actions/buttons
![image](https://user-images.githubusercontent.com/12898497/217042574-9e2dec1f-da57-4abb-b571-0fe4fb2080cb.png)

Ideally, this plugin continued using the theme for actions/buttons.

**Comment by drodil** [comment]
Thanks for the report! Good findings and should be quite easy to fix. The plugin uses the default MUI components and styles with only few exceptions. It's a bit weird that the default theme renders these so badly. Have to try this out with the light theme a bit more and maybe convert these buttons to follow the primary button style, like you suggested.

I will check this tomorrow!

**Comment by drodil** [comment]
This is now released in 1.3.1, please try it out!

**Comment by alecjacobs5401** [comment]
Awesome, thanks @drodil! Updating now - looks great!
