### ISSUE TITLE
feat: filtering of issues

### ISSUE THREAD

**Issue by drodil** [drodil/backstage-plugin-qeta#4]
There should be a filter possibility in the question list that allows

- Changing the order of the issues (latest activity, score, latest)
- Changing the number of issues shown on a single page
- Filtering only questions without answers
- Filtering only questions without a correct answer
- Filtering questions with tags

The filters should be hidden behind a button that opens these options for the user. The filters should also include the filters the page adds (for example user or tag)

**Comment by drodil** [comment]
Still missing filtering by tags and component. If QuestionContainer is given tags or component as property, these should be hidden.

**Comment by drodil** [comment]
Also nice addition would be "No votes" checkbox

**Comment by drodil** [comment]
Also besides tags and components filters, user filter would be nice

**Comment by Revyy** [comment]
Hey! Great work on this plugin!
One other filter that would be nice to have on the "All questions" page is a free-text search filter.
Similar to how it works for Techdocs where you can search within a documentation page, if you are familiar with that :) 

You can off course search using the global search in backstage but I think it would make sense to be able to do some basic free-text filtering on the questions page as well.

**Comment by drodil** [comment]
@Revyy thanks for the feedback and great idea! I might have time to take a look at this in near future. If you are willing to create a PR, you are also free to do that 👍

**Comment by drodil** [comment]
Closing this as there is quite nice filtering capabilities now
