### ISSUE TITLE
feat: answer card thread / replies

### ISSUE THREAD

**Issue by anestor6** [drodil/backstage-plugin-qeta#42]
Had a situation where a question got several answers and resulted in a new discussion in which users were responding to each other out of sync. Think it would be a great feature to add a reply option on the AnswerCard component that would create a thread on that answer. Thoughts?

**Comment by drodil** [comment]
Good idea, it could be more like a comment on an answer or question. Just have to figure out when I have time to look at this. Especially how to render it, the backend should be pretty straight forward.
