### ISSUE TITLE
feat: Configure max-width of the content on the question page

### ISSUE THREAD

**Issue by Revyy** [drodil/backstage-plugin-qeta#44]
Hey!

Currently the content on the question page fills the entire remaining space. 
This makes questions and answers a bit annoying to read on bigger screens as you need to move your head/eyes to read all of the text.

It would be cool if it was possible to set a max-width and have it be centered similarly to how it is on stackoverflow: [random stackoverflow question](https://stackoverflow.com/questions/75731623/count-based-on-criteria-r).

As an example, you can set maxWidth for a Container(from material ui) this way, using breakpoints. 
`<Container maxWidth="md"></Container>`

**Comment by drodil** [comment]
Good idea, thanks. I actually had similar issue when using bigger screen but haven't got time yet to do anything.
