### ISSUE TITLE
bug: Internal server error on search.

### ISSUE THREAD

**Issue by JulianKurzOTTO** [drodil/backstage-plugin-qeta#52]
We frequently experience internal server errors from Backstage's search function. Debugging this lead to [this line](https://github.com/backstage/backstage/blob/master/plugins/search-backend-node/src/engines/LunrSearchEngine.ts#L327) failing, because it expects all indexable fields to be a string. When there was a match within `tags` (array) or `score` (number), this crashes the search.

The backstage documentation is not entirely clear about it, but it looks like an `IndexableDocument` may only have string fields.

**Comment by drodil** [comment]
What search backend are you using? At least with opensearch it works fine so just wondering if you are using something else that doesn't support it.

**Comment by drodil** [comment]
Ah, it' Lunr. Might be that tags need to be removed from the collator to fix this.
