### ISSUE TITLE
feat: Resolve author username to displayName

### ISSUE THREAD

**Issue by belech** [drodil/backstage-plugin-qeta#56]
In the Backstage User entity specification, it's shown that a User entity can have a displayName (spec.profile.displayName) which is commonly used rather that the username in the frontend for better readabiltiy - so I'd propose to try to resolve also in the frontend qeta plugin to this displayName.

Proposed implementation can follow along the UserProfileCard of the org-plugin: https://github.com/backstage/backstage/blob/master/plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx#L65-L77

**Comment by drodil** [comment]
Let's wait for this https://github.com/backstage/backstage/pull/17474 before going further with this as it allows easier way to get displayName also for the entities linked to a question.

**Comment by LZING** [comment]
Can the displayed user field be changed from name to title? Because the name value we are using now is the employee's job number, we cannot see the employee's name. And it also supports using title as the display name in backstage.

**Comment by drodil** [comment]
@LZING as said in the comment above, I want to wait for the entityPresentationApi from Backstage

**Comment by drodil** [comment]
This is now implemented, closing the issue
