### ISSUE TITLE
Add ability to notify entity owners when new question is asked about an entity

### ISSUE THREAD

**Issue by Shocktrooper** [drodil/backstage-plugin-qeta#61]
One of my end users asked if there was a way to know when a new question was asked about an entity they own as they have to login to see any questions at all and it appears that this is not possible.  I would like to have potentially multiple routes to notify end user owners of new questions

E.G.: Email, teams notification, slack notification, banner for end user when they login to backstage(albeit this is half measure as the end user still has to navigate to backstage to even see this)

**Comment by drodil** [comment]
Yeah this has been asked previously as well and it's a valid feature request. I think it doesn't make sense to start building it to this plugin as there's discussion about having a notification framework in the backstage repo that Q&A (as well as other plugins) could utilize. So my take would be to wait for that and then integrate. 

Of course what could be done at this point is to have callbacks in the backend/frontend for posting a new question/answer. That way the application using this plugin could create their own logic to send for example notifications. This has also open issue and could be implemented IMO. 

What do you think?

**Comment by drodil** [comment]
See #55

**Comment by drodil** [comment]
As well as this https://github.com/backstage/backstage/issues/10652

**Comment by drodil** [comment]
Maybe the plugin could utilize the event framework for the callbacks: https://github.com/backstage/backstage/tree/master/plugins%2Fevents-backend

**Comment by drodil** [comment]
So little update here. I've made a PR to backstage upstream to support sending stuff from backend plugins to frontend: https://github.com/backstage/backstage/pull/18153

This should allow further development for notifications in https://github.com/backstage/backstage/issues/10652

Also, there's now support for the events backend directly from Q&A, see `docs/events.md`

**Comment by drodil** [comment]
A couple of new related issues in the backstage project:

https://github.com/backstage/backstage/pull/21889
https://github.com/backstage/backstage/pull/22099
https://github.com/backstage/backstage/pull/21728

**Comment by drodil** [comment]
This is now done with backstage notifications system, closing!
