### ISSUE TITLE
Back to questions does not redirect back to entity page

### ISSUE THREAD

**Issue by zcmander** [drodil/backstage-plugin-qeta#65]
If you have embedded Q&A page as a tab into entity page, like this:
![image](https://github.com/drodil/backstage-plugin-qeta/assets/2142965/5abc3af7-033e-4f6d-803d-d48c3223c8c1)

After selecting question there is a button called **Back to questions**.

But that redirect the user back to all questions, not the ones that relates to the entity to begin with.

Should we embed question page under the entity page as well, so there would be no reason to have the button in the first place or is there any other ideas how to handle? Maybe carry entity reference in URL?

**Comment by drodil** [comment]
No, there's no reference in URL. Other option is to use the navigation history from browser but that might lead to weird places. Maybe adding the reference to URL could be the best option. Or some combination of these.

**Comment by drodil** [comment]
Should be fixed in 1.13.0
