### ISSUE TITLE
Possibility to customize the question page

### ISSUE THREAD

**Issue by gabriel-dantas98** [drodil/backstage-plugin-qeta#66]
## Context

Before using the Q&A as our center for questions from the development teams, we used another tool that allowed us to add specific fields for us as the team responsible for answering or maybe some specific subject that helped us to quantify the main doubts of each subject or team.

## Proposal

We have the possibility to customize the Ask Question page, [maybe inspired by the format that TechDocs ](https://backstage.io/docs/features/techdocs/how-to-guides/#building-a-custom-home-page) does or adding the possibility of passing new options as a props to the AskForm.

**Comment by damolaobaleke** [comment]
Styling the questions page is a good shout, e.g being able to change the approved answer also in a question ?

**Comment by drodil** [comment]
@damolaobaleke you can change the approved answer, but at the moment it requires that you first unapproved the previous answer. Might be good idea to change the logic behind this.

**Comment by damolaobaleke** [comment]
@drodil  Sorry to be even more specific. I actually meant changing the styling of the approved answer lol. So e.g changing the color of the tick mark ?

**Comment by drodil** [comment]
Ah ok :) Maybe we could introduce some `className`s for different parts of the UI that could be overridden by the application. You think that would be sufficient?

**Comment by damolaobaleke** [comment]
Yes that would be awesome ! 🚀 

> Ah ok :) Maybe we could introduce some `className`s for different parts of the UI that could be overridden by the application. You think that would be sufficient?

**Comment by damolaobaleke** [comment]
I'm currently doing it this way but its pretty tacky 
```
for (let path of document.getElementsByTagName('path')){
    if(path.getAttribute('d') === 'M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z'){
      path.classList.add('approved-answer')
      path.style.fill = 'green'
    }

    // if(path.__reactFiber$lo3uijje688.memoizedProps.d === 'M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z'){
    //     console.log(path)
    //     path.classList.add('approved-answer')
    // }
  }
```

**Comment by drodil** [comment]
Yeah that's not maybe the best way :) Having class names in the plugin itself could help with this. I can check if I have time to do something.

**Comment by drodil** [comment]
Classes are now available in 1.12.0, is this enough to close this issue?

**Comment by gabriel-dantas98** [comment]
> This is quite broad request as is. Could you elaborate a bit? What kind of customization are you thinking of? I think all kind of customization to the question fields need support all the way to the database level which might be hard to do.
> 
> For us the current possibility to link components and tags have been sufficient so I would like to hear more what kind of additional categories are you using?

I think I need to think more about the problem, we can close the issue yes.

My team's current context is that while tags are a good mechanism, we'd like to have better ways of classifying questions.

As the tags are free and optional texts, it is difficult to have a standard so that teams that have context can filter the questions they can answer.

So at first I thought of suggesting adding new fields to the question, but maybe this is really complicated at the database level.

Perhaps some way of preconfiguring the tags would be interesting.

**Comment by drodil** [comment]
Hm. That might be a possibility (optionally of course) to have a list of tags that can be used and remove the free text option. Maybe this could be configurable in the app config.yaml to make it a bit easier to set up. I might try to come up with a solution if you don't want to make a contribution?

**Comment by drodil** [comment]
Created new feature that might help with this. See the commit above and `docs/config.md`
