### ISSUE TITLE
Allowing other users to make edits to questions

### ISSUE THREAD

**Issue by bkoski** [drodil/backstage-plugin-qeta#75]
It can be helpful to allow other users to edit questions, particularly to fix tags or add a missing entity reference.  Right now, the edit action is restricted to only questions you've authored directly.

For simple environments, it's usually pretty comfortable to allow this permission globally to all users.  What do you think about adding an `allowAllUsersToEditQuestions` app-config?  This could be false by default.

**Comment by drodil** [comment]
Yeah, makes sense as there is a separate column for updatedBy. Requires some UI changes though and also the new configuration. On the other hand, don't know if this should actually be done by utilizing the permission framework instead separate config flag, any opinions?

This also relates a bit to the moderator role discussed in another issue.
