### ISSUE TITLE
Descriptive qeta search document

### ISSUE THREAD

**Issue by cblnco** [drodil/backstage-plugin-qeta#78]
There are a few values in the current [qeta search document](https://github.com/drodil/backstage-plugin-qeta/blob/main/plugins/qeta-backend/src/search/collators/QetaCollatorFactory.ts#L45C1-L59C6). I think it could be helpful to have a document that is a bit more descriptive so we can have more information available in the client side.

We could include a `docType` value to identify document type individually, `author`, `answersCount` and `score`.
The result example of this document would look like this:
```json
{
  "document": {
    "title": "Hello Ask",
    "text": "Hello this is a sample question",
    "location": "/qeta/questions/1",
    "docType": "qeta",
    "author": "user:default/user",
    "answers": 0,
    "score": 1
  }
}
```
In my team we take advantage of the `docType` value with Backstage's Search API to have buckets of documents by `docType`. This could be something that could be helpful for other customers when making queries with the search API.

In the client side this could be leveraged to show more details to users:

![Screen Shot 2023-07-13 at 14 01 45](https://github.com/drodil/backstage-plugin-qeta/assets/57539967/993261cc-6200-408f-93ab-b013a2f34c6e)

I would like to know your thoughts on this suggestion @drodil.

**Comment by drodil** [comment]
Makes sense. This needs a new type definition that extends the IndexableDocument. Are you willing to create a PR?

**Comment by cblnco** [comment]
Yes, I'm willing to. I was thinking that we can have a new interface like so:
```ts
export interface QetaDocument extends IndexableDocument {
  docType: string;
  author: string;
  score: number;
  answers?: number;
}
```
And then `QetaCollatorFactory` would return `AsyncGenerator<QetaDocument>`.
What do you think @drodil?

**Comment by cblnco** [comment]
All right, thanks @drodil. I have made the following PR: #79 so we can close this Issue.
