### ISSUE TITLE
Export types 

### ISSUE THREAD

**Issue by antoniomuso** [drodil/backstage-plugin-qeta#84]
I am currently using `EventBroker` but I don't have types like   `Question`, `Answer`, `Vote` `Comment`, and so on.  is It possible to export these types?

**Comment by drodil** [comment]
Yeah makes sense. These types should be exported from the qeta-common plugin and also used for both backend/frontend plugins instead of having those duplicated. Are you willing to provide a PR for this refactoring?

**Comment by antoniomuso** [comment]
> Yeah makes sense. These types should be exported from the qeta-common plugin and also used for both backend/frontend plugins instead of having those duplicated. Are you willing to provide a PR for this refactoring?

I did it.

**Comment by drodil** [comment]
Closing as this was refactored in #85
