### ISSUE TITLE
chore: migrate to new backend system

### ISSUE THREAD

**Issue by drodil** [drodil/backstage-plugin-qeta#90]
See https://github.com/backstage/backstage/issues/18301

qeta-backend should be migrated as well

**Comment by Josh-Uvi** [comment]
Hey @drodil, I would like to work on this and create a PR when completed.

**Comment by drodil** [comment]
@Josh-Uvi any updates on this one?

**Comment by Josh-Uvi** [comment]
Hi @drodil, the PR is [here](https://github.com/drodil/backstage-plugin-qeta/pull/101)

**Comment by drodil** [comment]
@Josh-Uvi awesome, thanks!

**Comment by Josh-Uvi** [comment]
Hey @drodil, do you mind closing this issue? 
This [PR](https://github.com/drodil/backstage-plugin-qeta/pull/101) has been merged.
